---

- block:
    - name: Download influx binary to local folder
      become: false
      get_url:
        url: "https://dl.influxdata.com/influxdb/releases/influxdb2-client-{{ influx_version }}-linux-amd64.tar.gz"
        dest: "/tmp/influxdb2-client-{{ influx_version }}.linux-{{ go_arch }}.tar.gz"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack influx binary
      become: false
      unarchive:
        src: "/tmp/influxdb2-client-{{ influx_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/influxdb2-client-{{ influx_version }}-linux-{{ go_arch }}/influx"
      delegate_to: localhost
      check_mode: false

    - name: Propagate influx binaries
      copy:
        src: "/tmp/influxdb2-client-{{ influx_version }}-linux-{{ go_arch }}/influx"
        dest: "{{ _influx_binary_install_dir }}/influx"
        mode: 0755
        owner: root
        group: root
      when: not ansible_check_mode
  when: influx_binary_local_dir | length == 0

- name: propagate locally distributed influx binary
  copy:
    src: "{{ influx_binary_local_dir }}/influx"
    dest: "{{ _influx_binary_install_dir }}/influx"
    mode: 0755
    owner: root
    group: root
  when: influx_binary_local_dir | length > 0
