---
- import_tasks: preflight.yml
  tags:
    - influxdb_install
    - influxdb_configure
    - influxdb_run
    - influxdb
    - all

- import_tasks: install.yml
  become: true
  when:
    ( not __influxdb_is_installed.stat.exists ) or
    ( (__influxdb_current_version_output.stderr_lines | length > 0) and (__influxdb_current_version_output.stderr_lines[0].split(" ")[2] != influxdb_version) ) or
    ( (__influxdb_current_version_output.stdout_lines | length > 0) and (__influxdb_current_version_output.stdout_lines[0].split(" ")[2] != influxdb_version) ) or
    ( influxdb_binary_local_dir | length > 0 )
  tags:
    - influxdb_install
    - influxdb
    - all


- import_tasks: configure.yml
  become: true
  tags:
    - influxdb_configure
    - influxdb
    - all

- name: Ensure InfluxDB is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: influxdb
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - influxdb_run
    - influxdb
    - all
