---
- name: "Set up monitoring"
  hosts: "{{ target if target is defined else 'monitoring_servers' }}"
  become: true

  roles:
    - custom/base
    - when: monitoring_playbook_docker_installation_enabled | bool
      role: galaxy/geerlingguy.docker
      vars:
        docker_install_compose: false
    - custom/prometheus
    - custom/grafana
    - custom/node_exporter
    - custom/alertmanager
    - custom/influxdb
    - custom/telegraf
    - custom/influx
    - custom/uptime-kuma