---
- name: "Set up monitoring"
  hosts: "{{ target if target is defined else 'monitoring_servers' }}"
  become: true

  roles:
    - prometheus
    - grafana
    - node_exporter
    - alertmanager
    - influxdb
    - telegraf