---

- name: Ensure uptime-kuma paths exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ monitoring_user_username }}"
    group: "{{ monitoring_user_groupname }}"
  with_items:
    - {path: "{{ uptime_kuma_config_path }}", when: true}
    - {path: "{{ uptime_kuma_data_path }}", when: true}
    - {path: "{{ uptime_kuma_docker_src_files_path }}", when: true}
  when: "item.when | bool"

- name: Ensure environment file created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config/env.j2"
    dest: "{{ uptime_kuma_env_file }}"
    owner: "{{ monitoring_user_username }}"
    group: "{{ monitoring_user_groupname }}"
    mode: 0640

- name: Create uptime-kuma docker volume
  docker_volume:
    name: "{{ uptime_kuma_docker_volume }}"

- name: Ensure uptime-kuma image is pulled
  community.docker.docker_image:
    name: "{{ uptime_kuma_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ uptime_kuma_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else uptime_kuma_docker_image_force_pull }}"
  when: "not uptime_kuma_container_image_self_build | bool"
  register: result
  retries: "5"
  delay: "3"
  until: result is not failed

- name: Ensure uptime-kuma repository is present on self-build
  ansible.builtin.git:
    repo: "{{ uptime_kuma_docker_repo }}"
    version: "{{ uptime_kuma_docker_repo_version }}"
    dest: "{{ uptime_kuma_docker_src_files_path }}"
    force: "yes"
  become: true
  become_user: "{{ monitoring_user_username }}"
  register: uptime_kuma_git_pull_results
  when: "uptime_kuma_container_image_self_build | bool"

- name: Ensure uptime-kuma is built
  docker_image:
    name: "{{ uptime_kuma_docker_image }}"
    source: build
    force_source: "{{ uptime_kuma_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_mailer_git_pull_results.changed }}"
    build:
      dockerfile: Dockerfile
      path: "{{ uptime_kuma_docker_src_files_path }}"
      pull: true
  when: "uptime_kuma_container_image_self_build | bool"

- name: Ensure uptime-kuma.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/uptime-kuma.service.j2"
    dest: "{{ monitoring_systemd_path }}/uptime-kuma.service"
    mode: 0644
  register: uptime_kuma_systemd_service_result

- name: Ensure systemd reloaded after uptime-kuma.service installation
  ansible.builtin.service:
    daemon_reload: true
  when: "uptime_kuma_systemd_service_result.changed | bool"

- name: Ensure uptime-kuma.service restarted, if necessary
  ansible.builtin.service:
    name: "uptime-kuma.service"
    state: restarted
