---
- include: preflight.yml
  tags:
    - alertmanager_install
    - alertmanager_configure
    - alertmanager_run
    - all

- include: install.yml
  become: true
  tags:
    - alertmanager_install
    - all

- include: configure.yml
  become: true
  tags:
    - alertmanager_configure
    - all

- name: ensure alertmanager service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: alertmanager
    state: started
    enabled: true
  tags:
    - alertmanager_run
    - all

- name: Flush alertmangaer handlers after run.
  meta: flush_handlers
