---
- name: Copy the telegraf systemd service file
  template:
    src: telegraf.service.j2
    dest: /etc/systemd/system/telegraf.service
    owner: root
    group: root
    mode: 0644
  notify: restart telegraf

- block:
    - name: Create telegraf config directory
      file:
        path: "/etc/telegraf"
        state: directory
        owner: root
        group: root
        mode: u+rwX,g+rwX,o=rX

    - name: Copy the telegraf config file
      template:
        src: telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf
        owner: root
        group: root
        mode: 0644
      notify: restart telegraf
