---

# This needs to always run, because it populates `monitoring_user_uid` and `monitoring_user_gid`,
# which are required by many other roles.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup_monitoring_user.yml"
  tags:
    - always

- name: Ensure base path exists
  file:
    path: "{{ monitoring_base_data_path }}"
    state: directory
    mode: "{{ monitoring_base_data_path_mode }}"
  become: true
  with_items:
    - "{{ monitoring_base_data_path }}"
  tags:
    - always

- name: Preserve vars.yml on the server for easily restoring if it gets lost later on
  copy:
    src: "{{ vars_yml_snapshotting_src }}"
    dest: "{{ monitoring_base_data_path }}/vars.yml"
    mode: '0660'
  become: true
  when: "vars_yml_snapshotting_enabled|bool"
  tags:
    - always

- name: Ensure Matrix network is created in Docker
  community.docker.docker_network:
    name: "{{ monitoring_docker_network }}"
    driver: bridge